#!/sbin/busybox sh
# custom script helper by gm

DEFAULT_PROFILE=/res/customconfig/default.profile
CONFIG_XML=/res/customconfig/customconfig.xml
PROFILE_PATH=/data/.siyah
LAST_SELECTED=.active.profile
ACTIVE_PROFILE=${PROFILE_PATH}/${LAST_SELECTED}

print_config()
{
  cat $CONFIG_XML
}

select_profile()
{
  # if there is no such profile, create one
  if [ ! -f ${PROFILE_PATH}/${1}.profile ];then
    cp $DEFAULT_PROFILE ${PROFILE_PATH}/${1}.profile
  fi
  echo $1 > $ACTIVE_PROFILE
}

delete_profile()
{
  rm ${PROFILE_PATH}/${1}.profile
  # TODO: what to do if the deleted profile is active? shall we have a select request?
}

rename_profile()
{
  # move old profile to new
  mv ${PROFILE_PATH}/${1}.profile ${PROFILE_PATH}/${2}.profile

  # if old profile is active, set the new profile as active profile
  if [ "`cat $ACTIVE_PROFILE`" == "$1" ];then
    echo $2 > $ACTIVE_PROFILE
  fi
}

write_config()
{
  if [ "a$1" == "a" ];then
    _CONFIG_FILE=$PROFILE_PATH/`cat ${PROFILE_PATH}/${LAST_SELECTED}`.profile
  else
    _CONFIG_FILE=$PROFILE_PATH/${1}.profile
  fi

  rm -f /tmp/config.ini
  while IFS="=" read -r key value
  do
    evalexpr='eval "echo \$$key"'
    echo $key=`eval $evalexpr`
  done < $_CONFIG_FILE > /tmp/config.ini
  cp /tmp/config.ini $_CONFIG_FILE
  rm -f /tmp/config.ini
}

read_config()
{
  if [ "a$1" == "a" ];then
    _CONFIG_FILE=$PROFILE_PATH/`cat ${PROFILE_PATH}/${LAST_SELECTED}`.profile
  else
    _CONFIG_FILE=${1}
  fi


  eval `sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
    -e 's/;.*$//' \
    -e 's/[[:space:]]*$//' \
    -e 's/^[[:space:]]*//' \
    -e "s/^\(.*\)=\([^\"']*\)$/\1=\"\2\"/" \
   < $_CONFIG_FILE | grep = `
}

read_defaults ()
{
  read_config "$DEFAULT_PROFILE"
}

# some initialization code

if [ ! -f $PROFILE_PATH/$LAST_SELECTED ];then 
  echo default > $PROFILE_PATH/$LAST_SELECTED
fi

if [ ! -f $PROFILE_PATH/default.profile ];then
  cp $DEFAULT_PROFILE $PROFILE_PATH/default.profile
fi
